export const users = [
  {
    id: '75',
    name: 'Max',
    email: 'selatez@jaditew.cd',
    phone: '5552267199',
    password: 'TmtHXcwW00OmThNvu',
    username: 'Sherman',
    confirmed: 'quản trị viên',
  },
  {
    id: '32',
    name: 'Mason',
    email: 'nefer@ibagok.zm',
    phone: '3409279828',
    password: 'qYabtASyxWlON8t6',
    username: 'Mendez',
    confirmed: 'quản trị viên',
  },
  {
    id: '48',
    name: 'Mabelle',
    email: 'paub@jol.bf',
    phone: '6238138887',
    password: 'Wtetba4oBGUA70e1Q',
    username: 'Fletcher',
    confirmed: 'quản trị viên',
  },
  {
    id: '100',
    name: 'Landon',
    email: 'fef@tec.bd',
    phone: '1247923657',
    password: 'XzlZ6s2LRlA',
    username: 'Rivera',
    confirmed: 'quản trị viên',
  },
  {
    id: '62',
    name: 'Ruth',
    email: 'kezlon@witimpok.ai',
    phone: '4317509502',
    password: 'gVlbneVmA8tZ6IPY',
    username: 'Barton',
    confirmed: 'quản trị viên',
  },
  {
    id: '91',
    name: 'Ola',
    email: 'livjazuha@agnum.tr',
    phone: '7615260520',
    password: 'OJVeoNgfJ2OMDpmsq8fy',
    username: 'Mathis',
    confirmed: 'quản trị viên',
  },
  {
    id: '56',
    name: 'Lewis',
    email: 'uvzo@runjomi.cf',
    phone: '5584852015',
    password: 'lsN3XzHsp1B7',
    username: 'Wells',
    confirmed: 'quản trị viên',
  },
  {
    id: '77',
    name: 'Eugenia',
    email: 'rajepce@vocani.iq',
    phone: '4991168244',
    password: 'qFxNBrDPt',
    username: 'Barker',
    confirmed: 'quản trị viên',
  },
  {
    id: '24',
    name: 'Eugene',
    email: 'iwu@tuzlogeb.gg',
    phone: '9399753890',
    password: 'usYWMguiE5XXO',
    username: 'Butler',
    confirmed: 'quản trị viên',
  },
  {
    id: '61',
    name: 'Lydia',
    email: 'daf@vuefepe.lv',
    phone: '6391616417',
    password: 'rZQgLibXykhkK7Ik3g6',
    username: 'Pratt',
    confirmed: 'quản trị viên',
  },
  {
    id: '90',
    name: 'Marcus',
    email: 'vunzircir@vamzarcos.ad',
    phone: '1048427813',
    password: 'RiPWsa2Y5P9gRQ5TJ',
    username: 'Miller',
    confirmed: 'quản trị viên',
  },
  {
    id: '40',
    name: 'Winifred',
    email: 'fanfumke@ibevimo.fk',
    phone: '2041287357',
    password: '1pf3saSErXUEZyuWY',
    username: 'Singleton',
    confirmed: 'quản trị viên',
  },
  {
    id: '53',
    name: 'Mollie',
    email: 'tafi@tusdenen.et',
    phone: '4681187932',
    password: 'MIpvm7RrvUeqxK',
    username: 'Sims',
    confirmed: 'quản trị viên',
  },
  {
    id: '36',
    name: 'Sarah',
    email: 'sibwekawu@jeke.kg',
    phone: '9882872957',
    password: '2Qg98',
    username: 'Rowe',
    confirmed: 'quản trị viên',
  },
];
