export const data = [
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
  {
    id: '',
    name: 'Hội sở Vietcombank',
    address: '198 Trần Quang Khải, Hà Nội',
    businessType: 'Ngân hàng',
    contacUser: 'Hoàng Việt Anh',
    contacUserPhone: '0966888123',
    maintenanceDate: '15/01/2023',
    tag: ['@Ca_bocongan', '@Ca_bocongan'],
  },
];
